name: build

on:
  push:
    branches: ["main", "v[0-9]+.[0-9]+.x"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: "stable"
            features: ""
          - toolchain: "stable"
            features: "--all-features"
          - toolchain: "stable"
            features: "--no-default-features"
          - toolchain: "beta"
            features: "--all-features"
          - toolchain: "nightly"
            features: "--all-features"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build ${{ matrix.features }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features
      - run: cargo test --all-features --examples
  build_wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "stable"
          targets: "wasm32-unknown-unknown"
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --target wasm32-unknown-unknown --no-default-features --features "ndarray crc32c gzip sharding transpose async"
        working-directory: ./zarrs
  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "stable"
      - run: cargo test --all-features
      - run: cargo test --all-features --examples
  test_macos:
    strategy:
      fail-fast: false
      matrix:
        runner: ["macos-15-intel", "macos-latest"]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "stable"
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features
      - run: cargo test --all-features --examples
  test_s390x:
    runs-on: ubuntu-latest
    steps:
      - name: Setup multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset
      - name: ubuntu-core:s390x-focal
        uses: docker://multiarch/ubuntu-core:s390x-focal
        with:
          args: >
            bash -c
            "uname -a &&
            lscpu | grep Endian 
            "
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "stable"
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features
      - run: cargo test --all-features --examples
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-features -- -D warnings
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: RUSTDOCFLAGS="--deny warnings" cargo doc --all-features --no-deps
  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
  minimal-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-hack cargo-minimal-versions --locked
      - run: cargo minimal-versions check --all-features --workspace --exclude zarrs_object_store
  msrv-1-91:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.91"
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-hack cargo-minimal-versions --locked
      - run: cargo minimal-versions check --all-features -p zarrs -p zarrs_chunk_key_encoding -p zarrs_codec -p zarrs_chunk_grid
  msrv-1-88:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.88"
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-hack cargo-minimal-versions --locked
      - run: cargo minimal-versions check --all-features -p zarrs_plugin
  # msrv-1-85:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: dtolnay/rust-toolchain@master
  #       with:
  #         toolchain: "1.85"
  #     - uses: Swatinem/rust-cache@v2
  #     - run: cargo install cargo-hack cargo-minimal-versions --locked
  #     - run: cargo minimal-versions check --all-features -p zarrs_object_store
  msrv-1-82:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.82"
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-hack cargo-minimal-versions --locked
      - run: sed -i 's/edition = "2024"/edition = "2021"/' */Cargo.toml \
      - run: cargo minimal-versions check --all-features -p zarrs_storage -p zarrs_filesystem
  # msrv-1-77:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: dtolnay/rust-toolchain@master
  #       with:
  #         toolchain: "1.77"
  #     - uses: Swatinem/rust-cache@v2
  #     - run: cargo install cargo-hack@0.6.39 cargo-minimal-versions@0.1.33 --locked
  #     - run: sed -i 's/edition = "2024"/edition = "2021"/' zarrs/Cargo.toml
  #     - run: cargo minimal-versions check --all-features -p zarrs_metadata -p zarrs_metadata_ext # Needs minimal-versions PR #1
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly install cargo-llvm-cov --locked
      - run: cargo +nightly llvm-cov --all-features --doctests --lcov --output-path lcov.info
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
