name: Zarr Conformance Tests
on:
  workflow_dispatch:
  schedule:
    - cron: '17 3 * * 0'

jobs:
  conformance-tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "stable"
      - uses: Swatinem/rust-cache@v2
      - run: cargo install --path zarrs_conformance
      - uses: Bisaloo/zarr-conformance-tests@main
        with:
          zarr-cli: zarrs_conformance
